services:
  scraper:
    build: .
    image: forgejo.rodinny.cloud/valorcz/tvwatch:latest
    container_name: tv-scraper
    # Override the default entrypoint
    entrypoint: tvwatch-bot
    env_file:
      - .env.docker
    volumes:
      # Maps the local ./data folder to the container's /app/data folder
      - ./data:/app/data
      - ./download:/download
    # Bot service
    restart: unless-stopped
